# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/exarchos/Downloads/Linux_Unreal_Engine_5.7.4

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	simulator-Android-DebugGame  \
	simulator-Android-Development  \
	simulator-Android-Shipping  \
	simulator-Linux-DebugGame  \
	simulator-Linux-Development  \
	simulator-Linux-Shipping  \
	simulator-LinuxArm64-DebugGame  \
	simulator-LinuxArm64-Development  \
	simulator-LinuxArm64-Shipping  \
	simulator \
	simulatorEditor-Linux-DebugGame  \
	simulatorEditor-Linux-Development  \
	simulatorEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend simulatorEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug simulatorEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

simulator-Android-DebugGame:
	 $(BUILD) simulator Android DebugGame  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulator-Android-Development:
	 $(BUILD) simulator Android Development  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulator-Android-Shipping:
	 $(BUILD) simulator Android Shipping  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulator-Linux-DebugGame:
	 $(BUILD) simulator Linux DebugGame  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulator-Linux-Development:
	 $(BUILD) simulator Linux Development  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulator-Linux-Shipping:
	 $(BUILD) simulator Linux Shipping  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulator-LinuxArm64-DebugGame:
	 $(BUILD) simulator LinuxArm64 DebugGame  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulator-LinuxArm64-Development:
	 $(BUILD) simulator LinuxArm64 Development  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulator-LinuxArm64-Shipping:
	 $(BUILD) simulator LinuxArm64 Shipping  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulator: simulator-Linux-Development

simulatorEditor-Linux-DebugGame:
	 $(BUILD) simulatorEditor Linux DebugGame  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulatorEditor-Linux-Development:
	 $(BUILD) simulatorEditor Linux Development  -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" $(ARGS)

simulatorEditor: simulatorEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/exarchos/Projects/UnrealProjects/simulator_test5.7/simulator_test57.uproject" -Game 

.PHONY: $(TARGETS)
