
[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=5BB3BC46DA6444578D281AEBCD6FCB96

[StartupActions]
bAddPacks=False
;InsertPack=(PackSource="StarterContent.upack",PackName="StarterContent")

[SectionsToSave]
+Section=StartupActions
